### ISSUE TITLE
Zero Wing (megadrive)

### ISSUE THREAD

**Issue by meleu** [meleu/rascripts#3]
@DimensionZero Aqui estão algumas imagens

## Colocar algum tipo de "Master" nos badges abaixo para os cheevos de passar da fase sem morrer:

- fase 1
![01738](https://user-images.githubusercontent.com/8508804/34956183-35f381e4-fa0f-11e7-8743-2b7ab0654c53.png)

- fase 2
![01739](https://user-images.githubusercontent.com/8508804/34956229-62e3d88e-fa0f-11e7-8b61-a35e573938d9.png)

- fase 3
![01740](https://user-images.githubusercontent.com/8508804/34956263-8016d028-fa0f-11e7-850d-18d120939303.png)

- fase 4
![02032](https://user-images.githubusercontent.com/8508804/34956277-8d7b9456-fa0f-11e7-893f-a823165b9703.png)

- fase 5
![01742](https://user-images.githubusercontent.com/8508804/34956290-98062d78-fa0f-11e7-8666-5904b78f97ce.png)

- fase 6
![01743](https://user-images.githubusercontent.com/8508804/34956305-a601f204-fa0f-11e7-9e83-ff260dbb48e5.png)

- fase 7
![01744](https://user-images.githubusercontent.com/8508804/34956351-c512fb2a-fa0f-11e7-911f-9379baef6726.png)

- fase 8
**AINDA VOU PROVIDENCIAR**

## cheevos de power up

Essas bolinhas nos screenshots abaixo são os itens de power up. A gente chega ao máximo quando pega 3. Então o badge pode ser a imagem do item e um "x3" do lado.

![homing - focar no item vermelho](https://user-images.githubusercontent.com/8508804/34958050-4e3ae398-fa17-11e7-9a81-2e9ebdbb1a25.png)

![laser - focar no item azul](https://user-images.githubusercontent.com/8508804/34958051-4ead9c12-fa17-11e7-86ec-9477436498f6.png)

![valcan - focar no item verde](https://user-images.githubusercontent.com/8508804/34958053-4f603228-fa17-11e7-8c5c-066b6d46ff19.png)

**Comment by DimensionZero** [comment]
![wings 1](https://user-images.githubusercontent.com/35441332/34960459-095778c6-fa22-11e7-81c5-3d0a7bc510a4.jpg)

**Comment by DimensionZero** [comment]
![zig 1](https://user-images.githubusercontent.com/35441332/34965958-447c6fac-fa3f-11e7-934a-34f034a66c54.jpg)

**Comment by DimensionZero** [comment]
![zig 2](https://user-images.githubusercontent.com/35441332/34966282-c75ac566-fa41-11e7-9bc3-1b9cba844ea4.jpg)

**Comment by DimensionZero** [comment]
![Uploading zig 3.jpg…]()

**Comment by DimensionZero** [comment]
![zig 3](https://user-images.githubusercontent.com/35441332/34966450-e7ce3c50-fa42-11e7-8655-66c31b67b673.jpg)

**Comment by DimensionZero** [comment]
![zig 4](https://user-images.githubusercontent.com/35441332/34966562-d3b357a4-fa43-11e7-8789-21509553bd9e.jpg)

**Comment by DimensionZero** [comment]
![zig 5](https://user-images.githubusercontent.com/35441332/34966699-ac402066-fa44-11e7-9a77-83592d9c6871.jpg)

**Comment by DimensionZero** [comment]
![zig 6](https://user-images.githubusercontent.com/35441332/34966848-20ac2052-fa46-11e7-99b8-b5703e983fd1.jpg)

**Comment by DimensionZero** [comment]
![zig 7](https://user-images.githubusercontent.com/35441332/34966938-a56daf4a-fa46-11e7-9e00-55d75bfc1a25.jpg)

**Comment by DimensionZero** [comment]
![zig one](https://user-images.githubusercontent.com/35441332/34967050-23ca60ea-fa47-11e7-8b00-b77f754c68e8.jpg)

**Comment by DimensionZero** [comment]
![zig 1](https://user-images.githubusercontent.com/35441332/34967117-87a2de4e-fa47-11e7-9efd-dd8d05ded70b.jpg)

**Comment by meleu** [comment]
Para o meme cheevo de "all your base are belong to us" podemos simplesmente usar essa imagem aqui:

![all-your-base](https://user-images.githubusercontent.com/8508804/34968005-b78c1ff2-fa4d-11e7-9e93-d4d187233d49.png)

**Comment by DimensionZero** [comment]
![x1](https://user-images.githubusercontent.com/35441332/34968495-bf385ce0-fa50-11e7-8b61-e7d6301af94d.jpg)

**Comment by DimensionZero** [comment]
maninho eu tô tentando mas não vai

**Comment by DimensionZero** [comment]
https://mega.nz/#!8jgkRBqB!qTVDKiG5dstwJm7pSYmTzE_wgzzlpN0-WIc-os8zmo4 acesse esse link do mega e baixe o arquivo rar e extraia e vai tá lá das badges

**Comment by DimensionZero** [comment]
![boss final](https://user-images.githubusercontent.com/35441332/35168214-40a75268-fd3f-11e7-8704-60f7bf5abc37.jpg)

**Comment by DimensionZero** [comment]
![zig 8](https://user-images.githubusercontent.com/35441332/35168238-53e0af3c-fd3f-11e7-872f-58e9ec8a8988.jpg)

**Comment by DimensionZero** [comment]
![Uploading 9 lives.jpg…]()
